FROM phpdockerio/php56-fpm:latest
WORKDIR "/application"

# Fix debconf warnings upon build
ARG DEBIAN_FRONTEND=noninteractive

# Install selected extensions and other stuff
RUN apt-get update \
    && apt-get -y --no-install-recommends install  php5-memcached php5-mongo php5-mysql php5-pgsql php5-redis php5-sqlite php5-gd php5-gnupg php5-pecl-http php5-imap php5-ldap php5-mapscript php5-memcache php5-oauth php5-odbc php5-radius php5-phpdbg php5-ssh2 php5-svn php5-sybase \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

# Install git
RUN apt-get update \
    && apt-get -y install git \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

COPY public /application/public

# Install OCI8
RUN mkdir /opt/oracle

COPY instantclient-basic-linux.x64-12.1.0.2.0.zip /opt/oracle
COPY instantclient-sdk-linux.x64-12.1.0.2.0.zip /opt/oracle

RUN apt-get update \
    && apt-get -y install unzip

RUN unzip /opt/oracle/instantclient-basic-linux.x64-12.1.0.2.0.zip -d /opt/oracle
RUN unzip /opt/oracle/instantclient-sdk-linux.x64-12.1.0.2.0.zip -d /opt/oracle

RUN ln -s /opt/oracle/instantclient_12_1/libclntsh.so.12.1 /opt/oracle/instantclient_12_1/libclntsh.so
RUN ln -s /opt/oracle/instantclient_12_1/libocci.so.12.1 /opt/oracle/instantclient_12_1/libocci.so

RUN echo /opt/oracle/instantclient_12_1 > /etc/ld.so.conf.d/oracle-instantclient.conf

#RUN apt-get update \
#	&& apt-get -y install pecl_http-2.5.5

RUN ldconfig

RUN apt-get update \
	&& apt-get -y install php5-dev php-pear build-essential libaio1 
	# && php-xml php5-xml

RUN mv /usr/share/php/doc /usr/share/php/doc_bak

RUN printf "instantclient,/opt/oracle/instantclient_12_1\n" | pecl install oci8-2.0.12

RUN echo "extension = oci8.so" >> /etc/php5/fpm/php.ini
RUN echo "extension = oci8.so" >> /etc/php5/cli/php.ini
