SELECT
    LIQUID_PESERTA.id,
    liquid_peserta.LIQUID_ID,
    liquid_peserta.ATASAN_ID,
    liquid_peserta.BAWAHAN_ID,
    FEEDBACKS.id feedback_id,
    PENGUKURAN_PERTAMA.id PENGUKURAN_PERTAMA_id,
    PENGUKURAN_KEDUA.id PENGUKURAN_KEDUA_id
FROM
    LIQUID_PESERTA
        JOIN (
        SELECT
            LIQUID_ID,
            ATASAN_ID,
            BAWAHAN_ID
        FROM
            LIQUID_PESERTA
        WHERE LIQUID_PESERTA.DELETED_AT IS NULL
        GROUP BY
            LIQUID_ID,
            ATASAN_ID,
            BAWAHAN_ID
        HAVING (count(1) > 1)) lp2 ON (LIQUID_PESERTA.LIQUID_ID = lp2.liquid_id
        AND LIQUID_PESERTA.ATASAN_ID = lp2.atasan_id
        AND LIQUID_PESERTA.BAWAHAN_ID = lp2.bawahan_id)
        LEFT JOIN FEEDBACKS ON (FEEDBACKS.LIQUID_PESERTA_ID = LIQUID_PESERTA.id)
        LEFT JOIN PENGUKURAN_PERTAMA ON (PENGUKURAN_PERTAMA.LIQUID_PESERTA_ID = LIQUID_PESERTA.id)
        LEFT JOIN PENGUKURAN_KEDUA ON (PENGUKURAN_KEDUA.LIQUID_PESERTA_ID = LIQUID_PESERTA.id)

WHERE LIQUID_PESERTA.DELETED_AT IS NULL
ORDER BY
    LIQUID_PESERTA.BAWAHAN_ID
