select  ROW_NUMBER() OVER (Order by M_BUSINESS_AREA.DESCRIPTION ) AS Nomor,
       M_COMPANY_CODE.COMPANY_CODE AS COMPANY_CODE,
       M_COMPANY_CODE.DESCRIPTION AS COMPANY,
       M_BUSINESS_AREA.BUSINESS_AREA AS BUSINESS_AREA,
       M_BUSINESS_AREA.DESCRIPTION AS BUSINESS,
       LIQUIDS.ID as LIQUID_ID,
       LIQUIDS.FEEDBACK_START_DATE as PERIODE,
       CASE WHEN V_LIQUID_PESERTA_SNAPSHOT.KELOMPOK_JABATAN_ATASAN IS NULL
                 THEN 'LAINNYA'
           ELSE V_LIQUID_PESERTA_SNAPSHOT.KELOMPOK_JABATAN_ATASAN END AS LEVELL,
       count(distinct V_LIQUID_PESERTA_SNAPSHOT.NIP_ATASAN) as jml_atasan,
       COUNT(DISTINCT V_LIQUID_PESERTA_SNAPSHOT.NIP_BAWAHAN) AS jml_bawahan,
        count(DISTINCT FEEDBACKS.ID) as jml_feedback,
      CONCAT( ROUND((Count(DISTINCT FEEDBACKS.ID)* 100 / COUNT(DISTINCT V_LIQUID_PESERTA_SNAPSHOT.NIP_BAWAHAN))),'%') AS PERSEN_FEEDBACK,
        count(DISTINCT PENYELARASAN.ID) as JML_PENYELARASAN,
       CONCAT(ROUND((count(DISTINCT PENYELARASAN.ID)* 100 / count(DISTINCT V_LIQUID_PESERTA_SNAPSHOT.NIP_ATASAN))),'%') AS PERSEN_PENYELARASAN,
        count(PENGUKURAN_PERTAMA.ID)as JML_PENGUKURAN_PERTAMA,
      CONCAT( ROUND((count(PENGUKURAN_PERTAMA.ID)* 100 / COUNT(DISTINCT V_LIQUID_PESERTA_SNAPSHOT.NIP_BAWAHAN))),'%') AS PERSEN_PENGUKURAN_PERTAMA,
       COUNT( DISTINCT ACTIVITY_LOG_BOOK.ID) AS ACTIVITY_LOG,
       COUNT (PENGUKURAN_KEDUA.ID) AS JML_PENGUKURAN_KEDUA,
       CONCAT (ROUND((COUNT (PENGUKURAN_KEDUA.ID)* 100 / COUNT(DISTINCT V_LIQUID_PESERTA_SNAPSHOT.NIP_BAWAHAN))),'%') AS PERSEN_PENGUKURAN_KEDUA
from V_LIQUID_PESERTA_SNAPSHOT
left join M_BUSINESS_AREA on M_BUSINESS_AREA.BUSINESS_AREA = V_LIQUID_PESERTA_SNAPSHOT.BUSINESS_AREA_ATASAN
left join M_COMPANY_CODE on M_COMPANY_CODE.COMPANY_CODE = M_BUSINESS_AREA.COMPANY_CODE
left join LIQUIDS on LIQUIDS.ID = V_LIQUID_PESERTA_SNAPSHOT.LIQUID_ID
left join (SELECT * FROM FEEDBACKS WHERE FEEDBACKS.STATUS ='PUBLISHED') FEEDBACKS on FEEDBACKS.LIQUID_PESERTA_ID = V_LIQUID_PESERTA_SNAPSHOT.ID
left join PENGUKURAN_PERTAMA on PENGUKURAN_PERTAMA.LIQUID_PESERTA_ID = V_LIQUID_PESERTA_SNAPSHOT.ID
left join PENYELARASAN on penyelarasan.ATASAN_ID = V_LIQUID_PESERTA_SNAPSHOT.ATASAN_ID
LEFT JOIN ACTIVITY_LOG_BOOK ON ACTIVITY_LOG_BOOK.LIQUID_ID = V_LIQUID_PESERTA_SNAPSHOT.LIQUID_ID
left join PENGUKURAN_KEDUA ON PENGUKURAN_KEDUA.LIQUID_PESERTA_ID = V_LIQUID_PESERTA_SNAPSHOT.ID
where LIQUIDS.DELETED_AT is null
and liquids.STATUS ='PUBLISHED'
AND M_COMPANY_CODE.DESCRIPTION IS NOT NULL
group by M_COMPANY_CODE.COMPANY_CODE, M_COMPANY_CODE.DESCRIPTION, M_BUSINESS_AREA.BUSINESS_AREA, M_BUSINESS_AREA.DESCRIPTION, LIQUIDS.FEEDBACK_START_DATE, LIQUIDS.ID,
         CASE WHEN V_LIQUID_PESERTA_SNAPSHOT.KELOMPOK_JABATAN_ATASAN IS NULL
                 THEN 'LAINNYA'
           ELSE V_LIQUID_PESERTA_SNAPSHOT.KELOMPOK_JABATAN_ATASAN END
