select LIQUID_PESERTA.LIQUID_ID,
       LIQUID_PESERTA.ATASAN_ID,
       LIQUID_PESERTA.SNAPSHOT_ORGEH_1,
       LIQUID_PESERTA.SNAPSHOT_ORGEH_2,
       LIQUID_PESERTA.SNAPSHOT_ORGEH_3,
       LIQUID_PESERTA.SNAPSHOT_NAMA_ATASAN                                                       AS NAMA,
       LIQUID_PESERTA.SNAPSHOT_NIP_ATASAN                                                        as NIP,
       LIQUID_PESERTA.SNAPSHOT_JABATAN_ATASAN                                                    as JENJANG_JABATAN,
       LIQUID_PESERTA.SNAPSHOT_JABATAN2_ATASAN                                                   AS SEBUTAN_JABATAN,
       CONCAT(CONCAT(LIQUID_PESERTA.SNAPSHOT_UNIT_CODE, '-'), LIQUID_PESERTA.SNAPSHOT_UNIT_NAME) AS UNIT,
       count(LIQUID_PESERTA.ID)                                                                  as JUMLAH_BAWAHAN,
       COUNT(DISTINCT FEEDBACKS.ID)                                                              AS JUMLAH_FEEDBACK,
       COUNT(ACTIVITY_LOG_BOOK.ID)                                                               AS JUMLAH_ACTIVITY_LOG,
       TO_CHAR(LIQUIDS.PENGUKURAN_PERTAMA_START_DATE, 'DD MONTH YYYY',
               'NLS_DATE_LANGUAGE = INDONESIAN')                                                 AS PENGUKURAN_PERTAMA,
       TO_CHAR(LIQUIDS.PENGUKURAN_KEDUA_START_DATE, 'DD MONTH YYYY',
               'NLS_DATE_LANGUAGE = INDONESIAN')                                                 AS PENGUKURAN_KEDUA,
       replace(rtrim(xmlagg(xmlelement(e, FEEDBACKS.KELEBIHAN, '#').extract('//text()') order by FEEDBACKS.ID).getclobval(),', '), '&quot;','"')  AS KELEBIHAN_RAW,
       replace(rtrim(xmlagg(xmlelement(e, PENYELARASAN.RESOLUSI, '#').extract('//text()') order by PENYELARASAN.ID).getclobval(), ', '), '&quot;', '"') AS RESOLUSI_RAW,
       replace(rtrim(xmlagg(xmlelement(e, V_LIQUID_PENGUKURAN_PERTAMA.RESOLUSI, '#').extract('//text()') order by V_LIQUID_PENGUKURAN_PERTAMA.ID).getclobval(), ', '), '&quot;', '"') AS PENGUKURAN_PERTAMA_RAW,
       replace(rtrim(xmlagg(xmlelement(e, V_LIQUID_PENGUKURAN_KEDUA.RESOLUSI, '#').extract('//text()') order by V_LIQUID_PENGUKURAN_KEDUA.ID).getclobval(),', '), '&quot;', '"') AS PENGUKURAN_KEDUA_RAW
from LIQUID_PESERTA
    left join LIQUIDS
on LIQUIDS.ID = LIQUID_PESERTA.LIQUID_ID
    left join (SELECT * FROM FEEDBACKS WHERE FEEDBACKS.STATUS = 'PUBLISHED') FEEDBACKS
    on FEEDBACKS.LIQUID_PESERTA_ID = LIQUID_PESERTA.ID
    left join USERS on (USERS.NIP = LIQUID_PESERTA.SNAPSHOT_NIP_ATASAN)
    left join ACTIVITY_LOG_BOOK on (ACTIVITY_LOG_BOOK.CREATED_BY = users.id)
    left join PENYELARASAN on (PENYELARASAN.LIQUID_ID = LIQUID_PESERTA.LIQUID_ID and PENYELARASAN.ATASAN_ID = LIQUID_PESERTA.ATASAN_ID)
    left join V_LIQUID_PENGUKURAN_PERTAMA on (V_LIQUID_PENGUKURAN_PERTAMA.LIQUID_PESERTA_ID = LIQUID_PESERTA.ID)
    left join V_LIQUID_PENGUKURAN_KEDUA on (V_LIQUID_PENGUKURAN_KEDUA.LIQUID_PESERTA_ID = LIQUID_PESERTA.ID)
where LIQUIDS.DELETED_AT is null
  and LIQUIDS.STATUS = 'PUBLISHED'
GROUP BY
    LIQUID_PESERTA.LIQUID_ID,
    LIQUID_PESERTA.ATASAN_ID,
    LIQUID_PESERTA.SNAPSHOT_ORGEH_1,
    LIQUID_PESERTA.SNAPSHOT_ORGEH_2,
    LIQUID_PESERTA.SNAPSHOT_ORGEH_3,
    LIQUID_PESERTA.SNAPSHOT_NAMA_ATASAN,
    LIQUID_PESERTA.SNAPSHOT_NIP_ATASAN,
    LIQUID_PESERTA.SNAPSHOT_JABATAN_ATASAN,
    LIQUID_PESERTA.SNAPSHOT_JABATAN2_ATASAN,
    LIQUID_PESERTA.SNAPSHOT_UNIT_CODE,
    CONCAT(CONCAT(LIQUID_PESERTA.SNAPSHOT_UNIT_CODE, '-'), LIQUID_PESERTA.SNAPSHOT_UNIT_NAME),
    TO_CHAR(LIQUIDS.PENGUKURAN_PERTAMA_START_DATE, 'DD MONTH YYYY', 'NLS_DATE_LANGUAGE = INDONESIAN'),
    TO_CHAR(LIQUIDS.PENGUKURAN_KEDUA_START_DATE, 'DD MONTH YYYY', 'NLS_DATE_LANGUAGE = INDONESIAN')
ORDER BY UNIT, JENJANG_JABATAN

